from __future__ import annotations


WORD_CATEGORIES: dict[str, str] = {
    "abrazo": "acciones",
    "actor": "personas",
    "adulto": "personas",
    "aeropuerto": "transporte",
    "alguien": "personas",
    "alto": "personas",
    "amor": "acciones",
    "arreglar": "acciones",
    "asustar": "acciones",
    "autobus": "transporte",
    "avion": "transporte",
    "ayuda": "acciones",
    "bajo": "personas",
    "bebe": "personas",
    "biblioteca": "lugares",
    "bofetada": "acciones",
    "bombero": "personas",
    "bonito": "personas",
    "buena_persona": "personas",
    "buscar": "acciones",
    "callar": "acciones",
    "carpintero": "personas",
    "centro": "lugares",
    "cerrar": "acciones",
    "ciego": "personas",
    "cine": "lugares",
    "circo": "lugares",
    "comer": "acciones",
    "costura": "personas",
    "creer": "acciones",
    "debil": "personas",
    "delgado": "personas",
    "detener": "acciones",
    "doctor": "personas",
    "dormir": "acciones",
    "edificio": "lugares",
    "el": "personas",
    "ella": "personas",
    "ellas": "personas",
    "ellos": "personas",
    "estilista": "personas",
    "feo": "personas",
    "fuerte": "personas",
    "gordo": "personas",
    "guardar": "acciones",
    "hacer": "acciones",
    "hombre": "personas",
    "hospital": "lugares",
    "hotel": "lugares",
    "joven": "personas",
    "jugar": "acciones",
    "lanzar": "acciones",
    "limpiar": "acciones",
    "llorar": "acciones",
    "maestro": "personas",
    "mala_persona": "personas",
    "mecanico": "personas",
    "mercado": "lugares",
    "mentir": "acciones",
    "mesero": "personas",
    "metro": "transporte",
    "motocicleta": "transporte",
    "mudo": "personas",
    "mujeres": "personas",
    "museo": "lugares",
    "ninguno": "personas",
    "nino": "personas",
    "nosotras": "personas",
    "nosotros": "personas",
    "oir": "acciones",
    "olvidar": "acciones",
    "ordenar": "acciones",
    "policia": "personas",
    "presidente": "personas",
    "recoger": "acciones",
    "reir": "acciones",
    "restaurante": "lugares",
    "secretaria": "personas",
    "sordo": "personas",
    "supermercado": "lugares",
    "taxi": "transporte",
    "tractor": "transporte",
    "tren": "transporte",
    "tu": "personas",
    "ustedes": "personas",
    "yo": "personas",
    "zapatero": "personas",
}

WORD_CATEGORIES.update(
    dict.fromkeys(
        [
            "buenos_dias",
            "buenas_tardes",
            "buenas_noches",
            "gracias",
            "por_favor",
            "nos_vemos",
            "adios",
        ],
        "saludos",
    )
)

WORD_CATEGORIES.update(
    dict.fromkeys(
        [
            "dia",
            "hora",
            "semana",
            "minutos",
            "segundos",
            "lunes",
            "martes",
            "miercoles",
            "jueves",
            "viernes",
            "sabado",
            "domingo",
            "enero",
            "febrero",
            "marzo",
            "abril",
            "mayo",
            "junio",
            "julio",
            "agosto",
            "septiembre",
            "octubre",
            "noviembre",
            "diciembre",
            "ano",
        ],
        "tiempo",
    )
)

WORD_CATEGORIES.update(
    dict.fromkeys(
        [
            "calificacion",
            "clase",
            "cuaderno",
            "escuela",
            "lapiz",
            "lectura",
            "lenguaje_de_senas",
            "examen",
            "escritura",
            "borrador",
            "sacapuntas",
            "regla",
            "colores",
            "cuarto",
            "bano",
            "cocina",
            "cama",
            "casa",
            "closet",
            "cortina",
            "cuna",
            "techo",
            "piso",
            "escaleras",
            "escoba",
            "lampara",
            "mesa",
            "pared",
            "pasillo",
            "cristal",
            "ventana",
            "puerta",
        ],
        "casa y escuela",
    )
)

WORD_CATEGORIES.update(
    dict.fromkeys(
        [
            "abuela",
            "abuelo",
            "esposa",
            "esposo",
            "familia",
            "hermana",
            "hermano",
            "hijo",
            "hija",
            "papa",
            "mama",
            "novia",
            "novio",
            "prima",
            "primo",
            "sobrina",
            "sobrino",
            "tia",
            "tio",
        ],
        "familiares",
    )
)

WORD_CATEGORIES.update(
    dict.fromkeys(
        [
            "cuchara",
            "cuchillo",
            "plato",
            "vaso",
            "comida",
            "cena",
            "desayuno",
            "tenedor",
            "servilleta",
            "sal",
            "quiero_mas",
            "no_me_gusto",
            "cafe",
        ],
        "alimentos",
    )
)

WORD_CATEGORIES.update(
    dict.fromkeys(
        [
            "arete",
            "blusa",
            "bota",
            "camisa",
            "collar",
            "guante",
            "pantalon",
            "pijama",
            "shorts",
            "traje",
            "vestido",
            "zapatos",
            "falda",
            "ropa_interior",
        ],
        "ropa",
    )
)

WORD_CATEGORIES.update(
    dict.fromkeys(
        [
            "barba",
            "bigote",
            "brazo",
            "boca",
            "cabello",
            "cabeza",
            "cara",
            "pies",
            "dientes",
            "ojos",
            "orejas",
            "nariz",
            "oreja",
            "mejilla",
            "una",
        ],
        "cuerpo",
    )
)

WORD_CATEGORIES.update(
    dict.fromkeys(
        [
            "barco",
            "bicicleta",
            "camion",
            "helicoptero",
            "carro",
            "camioneta",
        ],
        "transporte",
    )
)

WORD_CATEGORIES.update(
    dict.fromkeys(
        [
            "aguascalientes",
            "baja_california_norte",
            "baja_california_sur",
            "campeche",
            "coahuila",
            "colima",
            "chiapas",
            "chihuahua",
            "sinaloa",
            "durango",
            "guanajuato",
            "guerrero",
            "hidalgo",
            "jalisco",
            "mexico",
            "michoacan",
            "morelos",
            "nayarit",
            "nuevo_leon",
            "oaxaca",
            "puebla",
            "queretaro",
            "quintana_roo",
            "san_luis_potosi",
            "sonora",
            "tabasco",
            "tamaulipas",
            "tlaxcala",
            "veracruz",
            "yucatan",
            "zacatecas",
        ],
        "lugares",
    )
)


def category_for_word(label: str) -> str:
    return WORD_CATEGORIES.get(label, "otros")